apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 18.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "1"
  name: root
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: kubeaid
  source:
    path: k8s/kubeaid-demo-local/argocd-apps
    repoURL: https://github.com/waridrox/kubeaid-config
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
